spring:
  application:
    name: eureka

#to tell eureka that don't register yourself to yourself, haha
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
